version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/crm-web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/api-core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      efcore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
          - "Microsoft.Extensions.Caching.Memory"
