// <auto-generated />
using Diax.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Diax.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DiaxDbContext))]
    [Migration("20260120120000_AddSnippetsTable")]
    partial class AddSnippetsTable
    {
    }
}
