// <auto-generated />
using System;
using Diax.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Diax.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DiaxDbContext))]
    [Migration("20260317000001_AddEmailOptimization")]
    partial class AddEmailOptimization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a placeholder Designer file. The actual properties would be generated
            // by EF Core. For simplicity during migration, just ensure the table exists.
#pragma warning restore 612, 618
        }
    }
}
