name: CI Test

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/test-ci.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "CI works!"
